version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8088:8088"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - ./traefik/letsencrypt:/etc/traefik # letsencrypt 데이터용 디렉토리 마운트
    networks:
      - web # web 네트워크 연결
    environment:
      - TRAEFIK_DASHBOARD_AUTH=autonotify:$2y$05$nk3Iz..3eY6AhbgWcPJz/.hv2Wvbnq6ddgSjrnoLsxDvMPWdm4Jga # 대시보드 인증 정보
    labels:
      # 보안 대시보드 라우터 설정 (traefik.yourdomain.com 교체 필요)
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.autonotify.store`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth@file"

networks:
  app-network:
    external: true

  web:
    external: true
