http:
  routers:
    django-app-router:
      rule: "Host(`api.autonotify.store`) && PathPrefix(`/api/v1`)"
      entryPoints:
        - websecure            # HTTPS(443)
      service: django-app-service
      tls:
        certResolver: letsencrypt
      middlewares:
        - cors                 # ✅ CORS 헤더 주입
        - rate-limit           # ✅ 기존 레이트 리밋 유지

  services:
    django-app-service:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

  middlewares:
    cors:                      # ✅ 신규 CORS 미들웨어
      headers:
        accessControlAllowOriginList:
          - "https://autonotify.store"
          - "https://www.autonotify.store"
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        addVaryHeader: true

    auth:
      basicAuth:
        users:
          - "autonotify:$2y$05$nk3Iz..3eY6AhbgWcPJz/.hv2Wvbnq6ddgSjrnoLsxDvMPWdm4Jga"

    dashboard-auth:
      basicAuth:
        users:
          - "autonotify:$2y$05$nk3Iz..3eY6AhbgWcPJz/.hv2Wvbnq6ddgSjrnoLsxDvMPWdm4Jga"

    rate-limit:
      rateLimit:
        average: 50
        burst: 100
