http:
  routers:
    django-app-router:
      rule: "Host(`api.autonotify.store`) && PathPrefix(`/api/v1`)"
      entryPoints:
        - websecure
      service: django-app-service
      tls:
        certResolver: letsencrypt
      middlewares:
        - cors
        - rate-limit

    portainer-router:
      rule: "Host(`portainer.autonotify.store`)"
      entryPoints:
        - websecure
      service: portainer-service
      middlewares:
        - dashboard-auth     # 포테이너 대시보드 인증

  services:
    django-app-service:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    portainer-service:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"

  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        addVaryHeader: true

    rate-limit:
      rateLimit:
        average: 50
        burst: 100

    auth:
      basicAuth:
        users:
          - "autonotify:$2y$05$nk3Iz..3eY6AhbgWcPJz/.hv2Wvbnq6ddgSjrnoLsxDvMPWdm4Jga"

    dashboard-auth:
      basicAuth:
        users:
          - "autonotify:$2y$05$nk3Iz..3eY6AhbgWcPJz/.hv2Wvbnq6ddgSjrnoLsxDvMPWdm4Jga"
