entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

  dashboard:
    address: ":8088"

api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog: {}

providers:
  docker:
    exposedByDefault: false
    network: web

  file:
    filename: "/etc/traefik/dynamic_conf.yml"

certificatesResolvers:
  letsencrypt:
    acme:
      email: sanghun@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    redirect-all:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal
      priority: 1
